version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "No dependencies to install."
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://bucket-for-lambda-2468/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name process_daily_json_file --s3-bucket bucket-for-lambda-2468 --s3-key deployment_package.zip
      - echo "Deployment complete!"